### ISSUE TITLE
Board moving in two different ways Matching pairs

### ISSUE THREAD

**Issue by Lia-JX-Li** [Amsterdam-Music-Lab/aml-experiments#489]
One way is shown in this following video as we talked about. 

https://github.com/Amsterdam-Music-Lab/aml-experiments/assets/65351308/d3c3e950-2aa2-4582-8dd4-bac050664f4f

The other way is that it moves when the screen is rescaled, as shown in the image below. And this is a bigger problem than the last one, because the card positions are displayed very differently, which makes it impossible to model them with positional factors.

<img width="646" alt="截屏2023-06-27 17 51 37" src="https://github.com/Amsterdam-Music-Lab/aml-experiments/assets/65351308/542b56bf-d00f-4bb7-a34d-66b5fde112ec">

**Comment by BeritJanssen** [comment]
I believe this was fixed in the meantime. Closing for now.
