### ISSUE TITLE
Continue button offscreen for Demographic Question 5/5 (on iPhone)

### ISSUE THREAD

**Issue by hhoning** [Amsterdam-Music-Lab/aml-experiments#543]
Continue button offscreen for Demographic Question 5/5 (on iPhone) 
(For version that went online 20230807 at https://acc.amsterdammusiclab.nl/tunetwins)

I do not know where this list came from, but it looks quite Eurocentric to me, if not mere British ("Vocational qualification at about 16 years of age (GCSE)" ?). Lets be wise, and reduce this to 5 or 6 categories that most people are familiar with.

![9C2ED49C-1098-41A2-8D86-6A2233E9069F_1_102_o](https://github.com/Amsterdam-Music-Lab/aml-experiments/assets/72495504/3c017cb8-9b82-430f-91a3-ede594a579aa)
![857FCBE5-ECA1-4CFA-9284-40110C04190D_1_102_o](https://github.com/Amsterdam-Music-Lab/aml-experiments/assets/72495504/4795b2e6-9b43-4aae-b754-4c765714b22a)

**Comment by BeritJanssen** [comment]
Two answer options were removed (GSCE, Asociate's degree), this should solve the problem.
