### ISSUE TITLE
Music preference: Audio problem

### ISSUE THREAD

**Issue by XHuang218** [Amsterdam-Music-Lab/aml-experiments#556]
one audio failed to play: section/1195/35466

**Comment by BeritJanssen** [comment]
This is the following track:
花粥 | 一腔诗意为了狗

**Comment by BeritJanssen** [comment]
Ah, I see the problem. The file is now called "Yi Qiang Shi Yi01.43.752.c1.mp3".

**Comment by XHuang218** [comment]
Yes, thats the problem. Shall I update the file name in CSV file you put in Teams?

**Comment by BeritJanssen** [comment]
I already updated it on the server.

**Comment by XHuang218** [comment]
Oh, I also updated  the file: https://amsuni.sharepoint.com/:x:/r/sites/FGW_RES_AIHR_ILLC_Amsterdam_Music_Lab/Gedeelde%20documenten/Music%20Preferences/[MusicalPreferencesPlaylist_new.csv](https://amsuni.sharepoint.com/:x:/r/sites/FGW_RES_AIHR_ILLC_Amsterdam_Music_Lab/Gedeelde%20documenten/Music%20Preferences/MusicalPreferencesPlaylist_new.csv?d=w3b7eb3eee5ec4ad1a579cda134c87303&csf=1&web=1&e=uaEHWL)?d=w3b7eb3eee5ec4ad1a579cda134c87303&csf=1&web=1&e=uaEHWL

**Comment by BeritJanssen** [comment]
Closing for now.
